(pill): adding pill component
VitauMX/vita-ui pull request #53
Opened 2021-06-09 22:03 UTC by dealparadize

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 📝 Additional Information

## ✅ Pull Request Checklist:

- [ ] :ok_hand: Design updates are approved by design team
- [ ] :white_check_mark: Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] :wheelchair: Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

2021-06-14 17:40 UTC, ruloCode approved these changes
LGTM

2021-06-17 17:30 UTC, DanielSepulveda reviewed
Algo que aun no entiendo bien es el caso de uso de este componente, es un boton? o es solo para desplegar informacion? Porque si se va a poder hacer click, creo que podría ser mejor desplegarlo como un botón no?

2021-06-17 17:30 UTC, DanielSepulveda commented on packages/pill/package.json
> +  "description": "pill component",
nit: la descripción del paquete hazla similar a la de los otros paquetes

2021-06-17 17:30 UTC, DanielSepulveda commented on packages/pill/src/Pill.tsx
> +import { variant } from 'styled-system';
Falta `styled-system` dentro de las dependencias del paquete

2021-06-17 17:30 UTC, DanielSepulveda commented on packages/pill/src/Pill.tsx
> +      'border-radius': '32px',
Parece que estos dos estilos estan presentes en las 3 variantes, creo que seria mejor si se abstraen de las variante y se agregan como estilos default del componente

2021-06-17 17:31 UTC, DanielSepulveda requested changes
Recuerda hacer los commits siguiendo la especificacion de conventional commits

2021-08-20 20:02 UTC, ruloCode approved these changes

2021-08-24 20:35 UTC, merged